# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/buildbot/buildbot/worker/probe_basic-dev/sources/debian/python3-probe-basic/usr/lib/python3.11/dist-packages/probe_basic_lathe/toolchange_dialog_pb.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(421, 284)
        Dialog.setModal(True)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setStyleSheet(".QFrame {\n"
"    color: white;\n"
"    font-family: \"Bebas Kai\";\n"
"    font-size: 16pt;\n"
"}\n"
"\n"
".QLabel {\n"
"    color: white;\n"
"    font-family: \"Bebas Kai\";\n"
"    font-size: 18pt;    \n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(12, 12, 12, 12)
        self.gridLayout.setSpacing(12)
        self.gridLayout.setObjectName("gridLayout")
        self.lblToolRemark = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblToolRemark.sizePolicy().hasHeightForWidth())
        self.lblToolRemark.setSizePolicy(sizePolicy)
        self.lblToolRemark.setMinimumSize(QtCore.QSize(0, 60))
        self.lblToolRemark.setStyleSheet("QLabel {\n"
"    border-style: transparent;\n"
"    border-color: rgb(235, 235, 235);\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: black;\n"
"    background: rgb(235, 235, 235);\n"
"    font: 75 16pt \"Bebas Kai\";\n"
"}")
        self.lblToolRemark.setFrameShape(QtWidgets.QFrame.Box)
        self.lblToolRemark.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lblToolRemark.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblToolRemark.setObjectName("lblToolRemark")
        self.gridLayout.addWidget(self.lblToolRemark, 3, 1, 1, 2)
        self.label_1 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Bebas Kai")
        font.setPointSize(18)
        self.label_1.setFont(font)
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.gridLayout.addWidget(self.label_1, 0, 1, 1, 1)
        self.lblToolNumber = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblToolNumber.sizePolicy().hasHeightForWidth())
        self.lblToolNumber.setSizePolicy(sizePolicy)
        self.lblToolNumber.setMinimumSize(QtCore.QSize(80, 50))
        self.lblToolNumber.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Bebas Kai")
        font.setPointSize(19)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblToolNumber.setFont(font)
        self.lblToolNumber.setStyleSheet("QLabel {\n"
"    border-style: transparent;\n"
"    border-color: rgb(235, 235, 235);\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: black;\n"
"    background: rgb(235, 235, 235);\n"
"    font: 19pt \"Bebas Kai\";\n"
"}")
        self.lblToolNumber.setFrameShape(QtWidgets.QFrame.Box)
        self.lblToolNumber.setAlignment(QtCore.Qt.AlignCenter)
        self.lblToolNumber.setObjectName("lblToolNumber")
        self.gridLayout.addWidget(self.lblToolNumber, 0, 2, 1, 1)
        self.btnDone = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDone.sizePolicy().hasHeightForWidth())
        self.btnDone.setSizePolicy(sizePolicy)
        self.btnDone.setMinimumSize(QtCore.QSize(0, 55))
        self.btnDone.setMaximumSize(QtCore.QSize(16777215, 55))
        self.btnDone.setStyleSheet("font: 75 17pt \"Bebas Kai\";")
        self.btnDone.setObjectName("btnDone")
        self.gridLayout.addWidget(self.btnDone, 4, 1, 1, 2)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(Dialog)
        self.btnDone.clicked.connect(Dialog.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Manual Tool Change"))
        self.lblToolRemark.setText(_translate("Dialog", "Remarks"))
        self.label_1.setText(_translate("Dialog", "Tool Change Requested, Insert tool"))
        self.lblToolNumber.setText(_translate("Dialog", "0"))
        self.btnDone.setText(_translate("Dialog", "ONCE TOOL IS LOADED - PRESS TO RESUME"))
